# Generated by Django 4.1.7 on 2023-04-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='UserName')),
                ('gender', models.CharField(blank=True, choices=[('M', '남성'), ('F', '여성')], max_length=2, verbose_name='Gender')),
                ('profile_img', models.ImageField(blank=True, help_text='gif, png, jpg 이미지 파일을 업로드 해주세요.', upload_to='user/profile_img/%Y/%m/%d', verbose_name='프로필 이미지')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='수정 날짜')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 상태')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자 권한')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자들',
                'db_table': 'user',
                'ordering': ['-id'],
            },
        ),
    ]
